POST http://localhost:7000/api/svi/user/register
Content-Type: application/json

{
    "first_name": "abdul",
    "last_name": "Mecury",
    "email": "jonasmecury@gmail.com",
    "phone": "09085746389",
    "gender": "male",
    "dob": "07/10/1990",
    "password": "11111111"
}

#### Get users
GET http://localhost:7000/api/svi/users

### Update user
PUT  http://localhost:7000/api/svi/user/update/:id
Content-Type: application/json

{
   "first_name": "John",
}

Delete users
DELETE  http://localhost:5000/api/v1/user/delete/:id
